### ISSUE TITLE
Issue downloading powershell universal via vscode ext. 

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/universal-code#10]
![image](https://user-images.githubusercontent.com/15201245/99694753-5ebc0f80-2a52-11eb-92e9-8a78ac91f073.png)

Been trying to download for awhile. Seems to be stuck. Checked appdata folder and nothing seems to be downloading. Any thoughts?

**Comment by fdk1034e** [comment]
Same issue here installing in vscode.
![image](https://user-images.githubusercontent.com/52499003/99731303-b9259200-2a8b-11eb-94ed-f8709a0f116e.png)
Install via extensions manager.
![image](https://user-images.githubusercontent.com/52499003/99731334-c3e02700-2a8b-11eb-9f3a-564c5aae1989.png)
Click Universal Dashboard icon in workbench and click download & start server prompt.
![image](https://user-images.githubusercontent.com/52499003/99731359-ccd0f880-2a8b-11eb-9fdc-444d0f609d04.png)
Get stuck.
![image](https://user-images.githubusercontent.com/52499003/99731386-d5c1ca00-2a8b-11eb-8507-7eae5b0f993a.png)

**Comment by adamdriscoll** [comment]
This has been fixed in 1.6.1. The VS Code extension should be on the marketplace shortly. If you upgrade it should download the correct link. We broke it with a name change to one of our packages.

**Comment by mikedhanson** [comment]
Looks like it downloaded fine now but throwing this error when trying to connect. "The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 1260)."

**Comment by adamdriscoll** [comment]
@mikedhanson - Can you try launching the process directly? It will probably provide a better error if it's failing to start it up. 

It will be in $Env:AppData\PowerShellUniversal. 

If you're really stuck, you can always [download from our website](https://ironmansoftware.com/downloads) and connect to the server by adjusting the settings. 

Just uncheck the setting to start the server and update the app token and URL and it should connect without trying to start the server. 

![image](https://user-images.githubusercontent.com/1256531/99740571-862fce00-2a8c-11eb-9ed7-1fee3141b841.png)

**Comment by mikedhanson** [comment]
Found out it was applocker tripping it since its not a signed binary. Thanks for the help :) 

![image](https://user-images.githubusercontent.com/15201245/99741518-f9d6d880-2a96-11eb-8fdb-e97692516654.png)

**Comment by fdk1034e** [comment]
> This has been fixed in 1.6.1. The VS Code extension should be on the marketplace shortly. If you upgrade it should download the correct link. We broke it with a name change to one of our packages.

@adamdriscoll Thank you- fixed issue for me.
