### ISSUE TITLE
"Samples" section is empty

### ISSUE THREAD

**Issue by potatoqualitee** [ironmansoftware/universal-code#31]
This is the latest version of VS Code with the latest extension

![image](https://user-images.githubusercontent.com/8278033/167639355-2c1fa956-a2eb-416a-83e4-1e6eda66f235.png)

I messed with the settings and restarted to no avail

![image](https://user-images.githubusercontent.com/8278033/167642025-28d7c9ad-8d3c-45df-93f2-759b731f3c50.png)

**Comment by adamdriscoll** [comment]
I've decided to remove the samples functionality from the extension in v5.2.0 and replace it with a simple link to the gallery repo. 

https://github.com/ironmansoftware/gallery
