### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by asuman-coder** [ironmansoftware/universal-code#4]
- Issue Type: `Performance`
- Extension Name: `powershell-universal`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\User\ironmansoftware.powershell-universal-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by adamdriscoll** [comment]
@asuman-coder - Do you have the cpuprofile file for this issue?
