### ISSUE TITLE
Dashboard import module import with wrong path

### ISSUE THREAD

**Issue by McAndersDK** [ironmansoftware/universal-code#6]
Hey Adam,
the component UniversalDashboard.Style import with the wrong path:
`Import-Module 'C:\ProgramData\PowerShellUniversal\Dashboard\Components\UniversalDashboard.Style\1.0.0\UniversalDashboard.Style.psd1\*.psd1' -Force`
it should be this:
`Import-Module 'C:\ProgramData\PowerShellUniversal\Dashboard\Components\UniversalDashboard.Style\1.0.0\*.psd1' -Force`

**Comment by adamdriscoll** [comment]
Fix in 1.5.0.
